### ISSUE TITLE
Items sync list

### ISSUE THREAD

**Issue by Chrometurtle** [henpemaz/Rain-Meadow#137]
**Crashes Game**
- [x] Scav Bomb
- [x] Explosive Spear
- [x] BeeHives
    Bee and AttachedBees need to be investigated as to how to sync those the best

**Throws error**
- [x] LTM neurons
- [x] 5P neurons
    MSC and Vanilla handle these differently

**Graphical Issue**
- [ ] FlareBomb

**Comment by youbitchoc** [comment]
we're deciding to ignore bees, clientside should simulate well enough
