### ISSUE TITLE
Not working on steamdeck/proton?

### ISSUE THREAD

**Issue by wicast** [henpemaz/Rain-Meadow#163]
I've installed and enabled this mod already, but proton doen't work with it.
![IMG_20240630_184927](https://github.com/henpemaz/Rain-Meadow/assets/2603937/ff2b87b4-2fa1-4edc-84de-e16094d265c9)
![IMG_20240630_185230](https://github.com/henpemaz/Rain-Meadow/assets/2603937/b8a20bc8-a534-4b3e-b666-99f2cde1b477)
![IMG_20240630_185641](https://github.com/henpemaz/Rain-Meadow/assets/2603937/9d8f66cd-d8e7-4d13-a0dc-49e6df90da37)

**Comment by wicast** [comment]
I've found the solution with https://docs.bepinex.dev/articles/advanced/proton_wine.html.
Add winhttp to the library list works fine. If game installed on an sd card, winetricks needs a permission from flatpak(will hint you).

Please add this info to the installation guideline.

**Comment by 6fears7** [comment]
Added in https://github.com/henpemaz/Rain-Meadow/commit/6b51e6674d0ab62d764e2888085a4d6f2127ba69, closing issue.
