### ISSUE TITLE
Buttons: Prevent double click

### ISSUE THREAD

**Issue by 6fears7** [henpemaz/Rain-Meadow#190]
Update simple button to prevent double click

**Comment by henpemaz** [comment]
Is it detecting clicks more than once, or are you trying to handle players double-clicking?

by default the game does support clicking buttons every other frame, but things like "start game" or "go to other menu" are gated with `proccessmanager.upcomingprocess == null`

**Comment by 6fears7** [comment]
Double-clicking on some buttons causes issues. 

"Join Lobby" for example, when double-clicked, locks user in infinite loading.

**Comment by henpemaz** [comment]
I'd still say it's not the buttons fault, I'd rather add a flag to the menu to avoid joining if there's already a join being processed
