### ISSUE TITLE
Story: disable collision in shelters, gates

### ISSUE THREAD

**Issue by youbitchoc** [henpemaz/Rain-Meadow#321]
should we make this an option? i kinda like the having to use spears as bunks / splitting off into diff dens

**Comment by 6fears7** [comment]
Definitely should be optional. I think  we should default to having collision to keep immersion like you said, players can disable at their discretion.

**Comment by 6fears7** [comment]
Closing in favor of: https://github.com/henpemaz/Rain-Meadow/issues/340
