### ISSUE TITLE
Story: Lobby needs character selection

### ISSUE THREAD

**Issue by 6fears7** [henpemaz/Rain-Meadow#43]
Not an urgent need yet, just opening to track it

**Comment by Chrometurtle** [comment]
This involves enabling More Slugcats Expansion

**Comment by 6fears7** [comment]
I do have a prototype I'm working on within MenuHooks that will check if MSC is enabled and return those slugcats if so, otherwise return the standard. Would also allow us down the road to actually register the characters to use emotes etc...  It also has to use a hook to unlock all of them so we'd have to decide if we want to match the single player Story's progression of Slugs or if we just want to open 'er up.

**Comment by 6fears7** [comment]
Gif was too large so:

![image](https://github.com/henpemaz/Rain-Meadow/assets/57415489/29aff365-510b-463d-9543-d53d0987ed03)


![image](https://github.com/henpemaz/Rain-Meadow/assets/57415489/348a80a9-d4da-42c1-be94-5de0aa69fcab)


Set's the avatar playingAs field to the current page index. I stripped out Night, MeadowOnline, and MeadowOnlineRemote slugcats because those require further discussion. I also overrode the LoadAs() to be the avatar's playingAs, though this does not change the overworld. Further discussion to come in future PR

**Comment by 6fears7** [comment]
Need to discuss with the team on this.

Setting the MeadowOnline player to the currently selected slug cat does work in-game. Tested with a client joining and they also became that slug cat. 

Might be a safer way to do this, also will need to eventually implement the correct beginning section for the slugcat. 

![image](https://github.com/henpemaz/Rain-Meadow/assets/57415489/a482398b-0641-4a1c-97e8-a3adf269bdd0)

**Comment by 6fears7** [comment]
Current commit on storymenu-rework branch works, but other slugcats' cycle 2's are not handled yet so when this implemented I will revert the character selection arrows to simply perform a `return` until we are ready

**Comment by 6fears7** [comment]
![image](https://github.com/henpemaz/Rain-Meadow/assets/57415489/e448cce0-4529-46af-9213-94682ae56fe0)

Added an additional remix option so clients can choose their own slugcats separate from the host. Can barely read the title with the background but it says, "Slugcat Select". 

 I have no idea if this will break things yet but could add a warning in the remix options menu to toggle this at their own risk
