### ISSUE TITLE
Story: Single-player (Non-Meadow) Player Readiness is always false

### ISSUE THREAD

**Issue by 6fears7** [henpemaz/Rain-Meadow#47]
https://github.com/henpemaz/Rain-Meadow/blob/623ea8917ade0aaa86c3e566de35d9e20baa6e93/Story/RainMeadow.StoryHooks.cs#L89

Noticed this earlier, but when you play Story solo, on sleep / death you cannot ready up.

**Comment by Chrometurtle** [comment]
The button shouldn't be showing up in single player in the first place. Will fix
