### ISSUE TITLE
Chat: typing "or" fast enough will activate dev tools and restart the cycle

### ISSUE THREAD

**Issue by SaddestUnderscore** [henpemaz/Rain-Meadow#472]
I gotta take care of that

**Comment by youbitchoc** [comment]
probably happens for other commands too so please don't special case this for "or", look into how [dev console](https://github.com/SlimeCubed/DevConsole) suppresses input

**Comment by SaddestUnderscore** [comment]
Mhm, have that in mind too

**Comment by youbitchoc** [comment]
https://github.com/SlimeCubed/DevConsole/blob/87f7cda02a4702ff94cf11fcba737438244bbfe5/DevConsole/GameConsole.cs#L744-L793
