### ISSUE TITLE
Story: How to handle death

### ISSUE THREAD

**Issue by Chrometurtle** [henpemaz/Rain-Meadow#48]
We need to sit down and discuss how we're handling death in story mode. Turn those into actionable items and work through it slowly

**Comment by 6fears7** [comment]
Drew it out for a reference to make sure I understand the current model:

![image](https://github.com/henpemaz/Rain-Meadow/assets/57415489/6ebb68a7-a14b-46fe-9e35-0ffcf75737df)




And then the desired state:

![image](https://github.com/henpemaz/Rain-Meadow/assets/57415489/cbc3df57-37f5-40d0-9be9-97d1a7f37463)


The game "director" doesn't have to be sophisticated in that sense. Could we take the current data being sent to Player 1 and instead hold it with a persistent object that lives through the entire game session so on updates we can free player 1 (or whoever's in charge) of governance over the game world to a neutral entity that observes and reports to all players?

**Comment by 6fears7** [comment]
A simple alternative (though admittedly narrow in scope, and excluding any game settings) could be an RPC counter when a user dies that if the death counter == number of participants, we run  game-over, otherwise they:

 1. Watch their dead body. 
 3. Watch another player's screen
 4. Jump between other player's screens.

**Comment by 6fears7** [comment]
This seems to be handled in the following hook:

`On.HUD.TextPrompt.orig_Update orig, TextPrompt self`

Did some brief testing with the following:


```
        private void PlayerGameOverUpdate(On.HUD.TextPrompt.orig_Update orig, TextPrompt self)
        {

            if (OnlineManager.lobby == null || OnlineManager.lobby.gameMode is not StoryGameMode)
            {
                orig(self);
                return;
            }

            if (self.gameOverMode)
            {

                foreach (var slugCat in OnlineManager.lobby.playerAvatars)
                {

                    if (slugCat.Value.realizedCreature.abstractCreature.world.game.AlivePlayers.Count > -1)
                    {
                        self.gameOverMode = false;  // Prevented a gameover despite my death at the hands of scavs
                        return; // Death isn't truly handled by network syncs, but at least we might know where the logic for death is
                    }
                }
                orig(self);

            }
        }
```

**Comment by 6fears7** [comment]
After discussion in Discord, the first stage of managing player death will be:

Game Over when all players are dead.
----


We can expand upon this as time and interest permit.

**Comment by Chrometurtle** [comment]
We're doing the dumb thing for now. We'll polish it further

**Comment by youbitchoc** [comment]
does #213 close this? or do we want an option to prevent host from initiating early gameover

**Comment by 6fears7** [comment]
Can't believe it's been 8 months. This is addressed.
