### ISSUE TITLE
Stuck on Joining Lobby Screen

### ISSUE THREAD

**Issue by TuffCat** [henpemaz/Rain-Meadow#595]
Whenever I try to join a lobby, it gives me the password prompt if it's a private lobby and that works fine. But once it gets to the Joining Lobby... screen, it never joins. The little slugcat animation just plays indefinitely. Same for creating lobbies- it gets stuck on the Creating Lobby... screen. If i click cancel while it's creating lobby, my lobby will still appear on the lobby list. I have restarted my computer and the issue persists. If someone else tries to join my lobby, they also get stuck on the joining lobby screen. I have also uninstalled and reinstalled the mod (via workshop) and the issue persists. 
I was able to join both a story and meadow lobby last night. It was only today that the issue started occurring. 
I'm using the workshop release of rain meadow, version 0.1.0.0

**Comment by 6fears7** [comment]
Please continue this convo in #log-dumps in our Discord. This is a mod issue with other mods. 

Recommended to disable all mods besides MSC, remix and meadow. Restart the game and try again

**Comment by TuffCat** [comment]
I don't know how to get to your discord.
It worked the day before with the exact same mods enabled and installed. None of them had been turned off or on between the day it worked and the day it didn't. None of them had been updated.
I will try to disable all mods and see if it works.

**Comment by TuffCat** [comment]
The fix did work but I need a way to be able to use other mods with this. Ican't continue this in your discord server because I don't know where to find your discord server.

**Comment by 6fears7** [comment]
https://discord.gg/Ze3qaYq49j
