### ISSUE TITLE
[Story] Not able to toggle/show player names on screen when 'ShowFriends' is disabled.

### ISSUE THREAD

**Issue by Creta5164** [henpemaz/Rain-Meadow#603]
Reproduction video : https://youtu.be/-s8ElxHS2R8

When `ShowFriends` is disabled in configration file (`AppData\LocalLow\Videocult\Rain World\ModConfigs\henpemaz_rainmeadow.txt`), cannot show player names on screen in story mode.

Version : `0.1.0.0` (Steam workshop)

**Comment by 6fears7** [comment]
Usernames are not managed there. You just need to hold "J" by default while in game to view usernames. Change the key in remix menu.

**Comment by Creta5164** [comment]
@6fears7 As you can see from the video, it didn't work at all.
It includes a shot of me checking to see if Capslock is enabled by default in the settings, and you can see that it doesn't work when both tab and hold are `false`.

**Comment by 6fears7** [comment]
Hm, don't touch the config file. Set ShowFriends to its default value and try again. 

Additionally, try changing the button from "toggle" to push-to-hold

**Comment by Creta5164** [comment]
So we keep tried to check about this.

- Default settings doesn't work (set to `false` and disabling toggle option)
- Disable all of mods except Remix, MSC, Meadow but still doesn't work

We decided to dump log about this.

https://discord.com/channels/1094716194180841602/1155268800669831270/1321466712453021796

**Comment by Creta5164** [comment]
Update : This issue needs more testing for specify the problem, I'll also upload more logs for investigate this issue.

**Comment by 6fears7** [comment]
Closed prematurely. This issue is present for others after confirming with playtesters

**Comment by 6fears7** [comment]
This has been resolved and will be available in a future update
