### ISSUE TITLE
Game crash after leaving an ongoing server when pressing the "exit" button on the main menu

### ISSUE THREAD

**Issue by mememan02** [henpemaz/Rain-Meadow#78]
The game sometimes crashes after leaving an ongoing server and attempting to close the game via the Exit button on the main menu (most instances have been after playing a Story mode server). The game will show the Unity crash handler (I do not have an image of this issue occurring to me at the present moment). This has occurred at least three separate times across multiple different playtest builds.

I currently have not found an effective way to reproduce this issue in a single-player lobby (although I have not done extensive testing); the crashes seem to happen most often after being in a lobby with several other players.

**Comment by Chrometurtle** [comment]
probably related to #111. Currently we don't handle players leaving/quitting, when the host quits I imagine things get crazy
