### ISSUE TITLE
Implement private lobbies for LAN 

### ISSUE THREAD

**Issue by 6fears7** [henpemaz/Rain-Meadow#93]
Related to #85

Posting the TODO here:

- I need a function that will open up a dialogue box with an input for password. I also need a OnClosed/OnFinished function that I can hook into when the dialogue box is closed out and I can read what password was inputted
- Password should be hashed

**Comment by Chrometurtle** [comment]
Not quite accurate. Closing, will make a new enhancement ticket after #85 is merged
